config/routes.rb
Rails.application.routes.draw do

  mount API::Root => "/"
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  scope '/tmpi' do
    get "/", to: "tmpi#index", as: "tmpi_index"
    post "/:id/confirm", to: "tmpi#confirm", as: "tmpi_confirm"
    post "/:id/decline", to: "tmpi#decline", as: "tmpi_decline"
  end
  get "support", to: "support#index"
  get "funfacts", to: "home#funfacts"
  post "support", to: "support#feedback", as: "submit_feedback"
  get "successful_password_change", to: "home#successful_password_change"

  scope "/cms" do
    unauthenticated :user do
      devise_scope :user do
        root to: "devise/sessions#new", as: "unauthenticated_root"
      end
    end

    authenticated :user do
      root to: "admin#index"
    end

    post "admin/dentists/:id/assignment",
      to: "admin/dentists#assignment",
      as: "admin_dentist_assignment"
    post "admin/dentists/:id/unassignment",
      to: "admin/dentists#unassignment",
      as: "admin_dentist_unassignment"
    delete "admin/dentists/:id/assignment/:clinic_assignment_id/schedule",
      to: "admin/dentists#delete_schedule",
      as: "admin_dentist_delete_schedule"
    post "admin/users/:id/toggle_status",
      to: "admin/users#toggle_status",
      as: "admin_toggle_user_status"

    get "admin/users/graph", to: "admin/users#graph"
    get "admin/appointments/graph", to: "admin/appointments#graph"

    get "admin/patients/appointments/graph", to: "admin/patients#graph"
    get "admin/patients/graph", to: "admin/patients#patients_graph"

    get "admin/secretaries/appointments/graph", to: "admin/secretaries#graph"
    get "admin/secretaries/graph", to: "admin/secretaries#secretaries_graph"

    get "admin/location/provinces", to: "admin/cities#provinces"

    get "admin/clinics/map", to: "admin/clinics#map"

    get "admin/rally_exports",
      to: "admin/rally_exports#registered_users",
      as: "admin_rally_exports"

    post "admin/users/:id/resend_code",
      to: "admin/users#resend_code",
      as: "admin_resend_user_code"

    get "admin/sms", to: "admin/sms#index", as: "admin_sms"
    post "admin/sms", to: "admin/sms#change", as: "admin_sms_change"

    authenticate :user do
      namespace :admin do
        resources :appointments, only: [:index, :show, :new, :create]
        resources :cities, only: [:index, :update]
        resources :clinics, except: :show
        resources :dentists
        resources :drafts, only: [:index, :update]
        resources :faqs, except: :show
        resources :feedbacks
        resources :hmos
        resources :patients
        resources :partner_signups, only: [:index, :update]
        resources :photos, only: [:destroy]
        resources :ratings, only: [:index, :show]
        resources :rating_suggestions, except: :show
        resources :secretaries
        resources :services
        resources :specialties
        resources :symptoms
        resources :users, only: [:index, :show, :edit, :update]
        resources :app_versions, except: [:new]
      end
    end
    devise_for :users, controllers: { passwords: "passwords" }
  end

  get "ios", to: "home#ios", as: "ios"
  get "download", to: "home#download", as: "mobile_download"
  # TODO : Uncomment on development
  # get '/rails/mailers' => "rails/mailers#index"
  # get '/rails/mailers/*path' => "rails/mailers#preview"
  get "docs", to: 'docs#index', as: 'docs'

  # Redirect all unknown path
  # and root to 404
  return404 = proc { [404, {}, [""]] }
  get "/", to: return404
  match "*path", to: return404, via: :get
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  created_at  :datetime         not null
#  description :string
#  duration    :integer
#  id          :integer          not null, primary key
#  name        :string
#  updated_at  :datetime         not null
#

class Service < ActiveRecord::Base
  has_many :appointments, dependent: :destroy
  has_many :service_assignments, dependent: :destroy
  has_many :dentists, through: :service_assignments, source: :assigned, source_type: 'User'
  has_many :clinics, through: :service_assignments, source: :assigned, source_type: 'Clinic'

  validates :name, uniqueness: true, presence: true
  validates :duration, presence: true

  def self.alphabetical(order: :asc)
    order(name: order)
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << ["Name","Description","Duration","created_at"]

      all.each do |service|
        csv << [service.name,service.description,service.duration,service.created_at]
      end
    end
  end

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  set_tab :services, only: :index

  # GET /admin/services
  def index
    @services = Service.all.order(created_at: :desc).page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.js
      format.csv { send_data Service.all.to_csv }
    end 
  end

  # GET /admin/services/1
  def show
  end

  # GET /admin/services/new
  def new
    @service = Service.new
  end

  # GET /admin/services/1/edit
  def edit
  end

  # POST /admin/services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to admin_services_path, notice: 'Dental service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/services/1
  def update
    if @service.update(service_params)
      redirect_to admin_services_path, notice: 'Dental service was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/services/1
  def destroy
    @service.destroy
    redirect_to admin_services_url, notice: 'Dental service was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_service
    @service = Service.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def service_params
    params.require(:service).permit(:name, :description, :duration)
  end
end

app/views/admin/services/_form.html.erb
<%= form_for [:admin, @service] do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% @service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <label>
    Name: <%= f.text_field :name %>
  </label>

  <label>
    Description: <br>
    <%= f.text_area :description %>
  </label>


  <label>
    Duration (in minutes): <%= f.text_field :duration %>
  </label>
<%= f.submit 'Submit', class: 'button' %>
<% end %>

app/views/admin/services/_services.html.erb
<table class="clean">
  <thead>
    <tr>
      <th>Name</th>
      <th width="100">Duration</th>
      <th width="150">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @services.each do |service| %>
    <tr>
    <td> <%= service.name %> </td>
    <td> <%= service.duration %> </td>
    <td>
      <%= link_to 'Edit', edit_admin_service_path(service), class: 'admin-custom-btn edit' %>
      <%= link_to 'Delete', admin_service_path(service), class: 'admin-custom-btn alert', method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/admin/services/edit.html.erb
<h4>Edit dental service</h4>
<%= render 'form' %>

app/views/admin/services/index.html.erb
<% content_for :title, 'Dental Services' %>
<%= content_tag(:p, notice, id: "notice") if notice %>

<h5 class="header">Dental Services</h5>
<div class="right">
  <%= link_to 'NEW', new_admin_service_path, class: 'admin-btn new' %></small>
  <%= link_to "EXPORT TO CSV", admin_services_path(format: "csv"), class: 'admin-btn export' %>
</div>

<div id="serviceLists">
  <%= render 'services' %>
</div>
<div id="paginator">
  <%= paginate @services, remote: true %>
</div>

app/views/admin/services/index.js.erb
$("#serviceLists").html("<%= escape_javascript(render("services")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@services, remote: true)) %>");

app/views/admin/services/new.html.erb
<h1>New service</h1>
<%= render 'form' %>

app/views/admin/services/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_service_path(@service) %> |
<%= link_to 'Back', admin_services_path %>