config/routes.rb
Rails.application.routes.draw do

  mount API::Root => "/"
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  scope '/tmpi' do
    get "/", to: "tmpi#index", as: "tmpi_index"
    post "/:id/confirm", to: "tmpi#confirm", as: "tmpi_confirm"
    post "/:id/decline", to: "tmpi#decline", as: "tmpi_decline"
  end
  get "support", to: "support#index"
  get "funfacts", to: "home#funfacts"
  post "support", to: "support#feedback", as: "submit_feedback"
  get "successful_password_change", to: "home#successful_password_change"

  scope "/cms" do
    unauthenticated :user do
      devise_scope :user do
        root to: "devise/sessions#new", as: "unauthenticated_root"
      end
    end

    authenticated :user do
      root to: "admin#index"
    end

    post "admin/dentists/:id/assignment",
      to: "admin/dentists#assignment",
      as: "admin_dentist_assignment"
    post "admin/dentists/:id/unassignment",
      to: "admin/dentists#unassignment",
      as: "admin_dentist_unassignment"
    delete "admin/dentists/:id/assignment/:clinic_assignment_id/schedule",
      to: "admin/dentists#delete_schedule",
      as: "admin_dentist_delete_schedule"
    post "admin/users/:id/toggle_status",
      to: "admin/users#toggle_status",
      as: "admin_toggle_user_status"

    get "admin/users/graph", to: "admin/users#graph"
    get "admin/appointments/graph", to: "admin/appointments#graph"

    get "admin/patients/appointments/graph", to: "admin/patients#graph"
    get "admin/patients/graph", to: "admin/patients#patients_graph"

    get "admin/secretaries/appointments/graph", to: "admin/secretaries#graph"
    get "admin/secretaries/graph", to: "admin/secretaries#secretaries_graph"

    get "admin/location/provinces", to: "admin/cities#provinces"

    get "admin/clinics/map", to: "admin/clinics#map"

    get "admin/rally_exports",
      to: "admin/rally_exports#registered_users",
      as: "admin_rally_exports"

    post "admin/users/:id/resend_code",
      to: "admin/users#resend_code",
      as: "admin_resend_user_code"

    get "admin/sms", to: "admin/sms#index", as: "admin_sms"
    post "admin/sms", to: "admin/sms#change", as: "admin_sms_change"

    authenticate :user do
      namespace :admin do
        resources :appointments, only: [:index, :show, :new, :create]
        resources :cities, only: [:index, :update]
        resources :clinics, except: :show
        resources :dentists
        resources :drafts, only: [:index, :update]
        resources :faqs, except: :show
        resources :feedbacks
        resources :hmos
        resources :patients
        resources :partner_signups, only: [:index, :update]
        resources :photos, only: [:destroy]
        resources :ratings, only: [:index, :show]
        resources :rating_suggestions, except: :show
        resources :secretaries
        resources :services
        resources :specialties
        resources :symptoms
        resources :users, only: [:index, :show, :edit, :update]
        resources :app_versions, except: [:new]
      end
    end
    devise_for :users, controllers: { passwords: "passwords" }
  end

  get "ios", to: "home#ios", as: "ios"
  get "download", to: "home#download", as: "mobile_download"
  # TODO : Uncomment on development
  # get '/rails/mailers' => "rails/mailers#index"
  # get '/rails/mailers/*path' => "rails/mailers#preview"
  get "docs", to: 'docs#index', as: 'docs'

  # Redirect all unknown path
  # and root to 404
  return404 = proc { [404, {}, [""]] }
  get "/", to: return404
  match "*path", to: return404, via: :get
end

app/models/hmo.rb
# == Schema Information
#
# Table name: hmos
#
#  created_at  :datetime         not null
#  description :text
#  id          :integer          not null, primary key
#  name        :string
#  updated_at  :datetime         not null
#

class HMO < ActiveRecord::Base
  has_one :logo, as: :imageable, class_name: 'Photo'
  has_many :appointments
  has_many :hmo_accreditations, dependent: :destroy
  has_many :dentists, through: :hmo_accreditations, source: :accredited, source_type: 'User'
  has_many :clinics, through: :hmo_accreditations, source: :accredited, source_type: 'Clinic'
  accepts_nested_attributes_for :logo

  validates :name, presence: true

  def self.search q = nil
    query = "%#{q}%"
    where('name ILIKE ?', query)
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << ["Name","Description","created_at"]

      all.each do |hmo|
        csv << [hmo.name,hmo.description,hmo.created_at]
      end
    end
  end

end

app/controllers/admin/hmos_controller.rb
class Admin::HMOsController < AdminController
  before_action :set_hmo, only: [:show, :edit, :update, :destroy]
  set_tab :hmos, only: :index

  # GET /admin/hmos
  # GET /admin/hmos.json
  def index
    @hmos = HMO.search(params[:q]).order(created_at: :desc).page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.js
      format.csv { send_data HMO.all.to_csv }
    end
  end

  # GET /admin/hmos/1
  # GET /admin/hmos/1.json
  def show
  end

  # GET /admin/hmos/new
  def new
    @hmo = HMO.new
    @logo = @hmo.build_logo
  end

  # GET /admin/hmos/1/edit
  def edit
  end

  # POST /admin/hmos
  # POST /admin/hmos.json
  def create
    @hmo = HMO.new(hmo_params)

    respond_to do |format|
      if @hmo.save
        format.html { redirect_to admin_hmo_url(@hmo), notice: 'HMO was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /admin/hmos/1
  # PATCH/PUT /admin/hmos/1.json
  def update
    respond_to do |format|
      if @hmo.update(hmo_params)
        format.html { redirect_to admin_hmo_url(@hmo), notice: 'HMO was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /admin/hmos/1
  # DELETE /admin/hmos/1.json
  def destroy
    @hmo.destroy
    respond_to do |format|
      format.html { redirect_to admin_hmos_url, notice: 'HMO was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_hmo
    @hmo = HMO.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def hmo_params
    params.require(:hmo).permit(:name, :description, logo_attributes: [:image])
  end
end

app/controllers/api/v1/hmo.rb
module API
  module V1
    class HMO < Grape::API
      resources :hmo do
        desc 'Return list of hmo'
        get jbuilder: 'v1/hmo/index' do
          @hmo = ::HMO.order(name: :asc)
        end
      end
    end
  end
end

app/helpers/admin/hmos_helper.rb
module Admin::HMOsHelper
end

app/views/admin/hmos/_form.html.erb
<%= form_for [:admin, @hmo], multipart: true  do |f| %>
  <% if @hmo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hmo.errors.count, "error") %> prohibited this hmo from being saved:</h2>

      <ul>
      <% @hmo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <label>
    Logo:
    <% if @hmo.logo.present? && !@hmo.logo.new_record? %>
      <%= image_tag @hmo.logo.image.url, width: 100 %>
      <br>
      <br>
    <% end %>
    <%= f.fields_for :logo, @logo do |logo_fields| %>
      <%= logo_fields.file_field :image %>
    <% end %>
  </label>

  <label>
    Name: <%= f.text_field :name %>
  </label>

  <label>
    Description: <br>
    <%= f.text_area :description %>
  </label>

  <div class="actions">
    <%= f.submit 'Submit', class: 'button' %>
  </div>
<% end %>

app/views/admin/hmos/_hmos.html.erb
<table class="clean">
  <thead>
    <tr>
      <th width="100"></th>
      <th>Name</th>
      <th width="170">Action</th>
    </tr>
  </thead>

  <tbody>
  <% @hmos.each do |hmo| %>
    <tr>
    <td><%= hmo.logo.present? ? image_tag(hmo.logo.image.url, width: 100) : "No logo" %></td>
    <td><%= hmo.name %></td>
    <td>
      <%= link_to 'Show', admin_hmo_path(hmo), class: 'admin-custom-btn success' %>
      <%= link_to 'Edit', edit_admin_hmo_path(hmo), class: 'admin-custom-btn edit' %>
      <%= link_to 'Destroy', admin_hmo_path(hmo), class: 'admin-custom-btn alert', method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/admin/hmos/edit.html.erb
<h4>Editing HMO</h4>
<%= render 'form' %>

app/views/admin/hmos/index.html.erb
<% content_for :title, 'HMOs' %>
<%= content_tag(:p, notice, id: "notice") if notice %>

<h5 class="header">HMOs</h5>
<div class="right">
  <%= link_to 'NEW', new_admin_hmo_path, class: 'admin-btn new' %></small>
  <%= link_to "EXPORT TO CSV", admin_hmos_path(format: "csv"), class: 'admin-btn export' %>
</div>

<%= form_tag admin_hmos_path, method: :get, remote: true, class: "admin-search-bar" do %>
  <%= text_field_tag :q, nil, placeholder: "Search" %>
<% end %>

<div id="hmoLists">
  <%= render 'hmos' %>
</div>
<div id="paginator">
  <%= paginate @hmos, remote: true %>
</div>

app/views/admin/hmos/index.js.erb
$("#hmoLists").html("<%= escape_javascript(render("hmos")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@hmos, remote: true)) %>");

app/views/admin/hmos/new.html.erb
<h4>New HMO</h4>
<%= render 'form' %>

app/views/admin/hmos/show.html.erb
<p id="notice"><%= notice %></p>

<label>
  Logo: <%= image_tag(@hmo.logo.image.url, width: 100)  if @hmo.logo.present? %>
</label>

<label>
  Name: <%= @hmo.name %>
</label>

<label>
  Description: <br>
  <%= @hmo.description %>
</label>