config/routes.rb
Rails.application.routes.draw do

  mount API::Root => "/"
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  scope '/tmpi' do
    get "/", to: "tmpi#index", as: "tmpi_index"
    post "/:id/confirm", to: "tmpi#confirm", as: "tmpi_confirm"
    post "/:id/decline", to: "tmpi#decline", as: "tmpi_decline"
  end
  get "support", to: "support#index"
  get "funfacts", to: "home#funfacts"
  post "support", to: "support#feedback", as: "submit_feedback"
  get "successful_password_change", to: "home#successful_password_change"

  scope "/cms" do
    unauthenticated :user do
      devise_scope :user do
        root to: "devise/sessions#new", as: "unauthenticated_root"
      end
    end

    authenticated :user do
      root to: "admin#index"
    end

    post "admin/dentists/:id/assignment",
      to: "admin/dentists#assignment",
      as: "admin_dentist_assignment"
    post "admin/dentists/:id/unassignment",
      to: "admin/dentists#unassignment",
      as: "admin_dentist_unassignment"
    delete "admin/dentists/:id/assignment/:clinic_assignment_id/schedule",
      to: "admin/dentists#delete_schedule",
      as: "admin_dentist_delete_schedule"
    post "admin/users/:id/toggle_status",
      to: "admin/users#toggle_status",
      as: "admin_toggle_user_status"

    get "admin/users/graph", to: "admin/users#graph"
    get "admin/appointments/graph", to: "admin/appointments#graph"

    get "admin/patients/appointments/graph", to: "admin/patients#graph"
    get "admin/patients/graph", to: "admin/patients#patients_graph"

    get "admin/secretaries/appointments/graph", to: "admin/secretaries#graph"
    get "admin/secretaries/graph", to: "admin/secretaries#secretaries_graph"

    get "admin/location/provinces", to: "admin/cities#provinces"

    get "admin/clinics/map", to: "admin/clinics#map"

    get "admin/rally_exports",
      to: "admin/rally_exports#registered_users",
      as: "admin_rally_exports"

    post "admin/users/:id/resend_code",
      to: "admin/users#resend_code",
      as: "admin_resend_user_code"

    get "admin/sms", to: "admin/sms#index", as: "admin_sms"
    post "admin/sms", to: "admin/sms#change", as: "admin_sms_change"

    authenticate :user do
      namespace :admin do
        resources :appointments, only: [:index, :show, :new, :create]
        resources :cities, only: [:index, :update]
        resources :clinics, except: :show
        resources :dentists
        resources :drafts, only: [:index, :update]
        resources :faqs, except: :show
        resources :feedbacks
        resources :hmos
        resources :patients
        resources :partner_signups, only: [:index, :update]
        resources :photos, only: [:destroy]
        resources :ratings, only: [:index, :show]
        resources :rating_suggestions, except: :show
        resources :secretaries
        resources :services
        resources :specialties
        resources :symptoms
        resources :users, only: [:index, :show, :edit, :update]
        resources :app_versions, except: [:new]
      end
    end
    devise_for :users, controllers: { passwords: "passwords" }
  end

  get "ios", to: "home#ios", as: "ios"
  get "download", to: "home#download", as: "mobile_download"
  # TODO : Uncomment on development
  # get '/rails/mailers' => "rails/mailers#index"
  # get '/rails/mailers/*path' => "rails/mailers#preview"
  get "docs", to: 'docs#index', as: 'docs'

  # Redirect all unknown path
  # and root to 404
  return404 = proc { [404, {}, [""]] }
  get "/", to: return404
  match "*path", to: return404, via: :get
end

app/models/dentist.rb
# == Schema Information
#
# Table name: users
#
#  avatar_content_type        :string
#  avatar_file_name           :string
#  avatar_file_size           :integer
#  avatar_updated_at          :datetime
#  confirmation_sent_at       :datetime
#  confirmation_token         :string
#  confirmed_at               :datetime
#  created_at                 :datetime
#  current_sign_in_at         :datetime
#  current_sign_in_ip         :string
#  disabled_at                :datetime
#  email                      :string           default(""), not null
#  encrypted_birthdate        :string
#  encrypted_birthdate_iv     :string
#  encrypted_mobile_number    :string
#  encrypted_mobile_number_iv :string
#  encrypted_password         :string           default(""), not null
#  first_name                 :string
#  id                         :integer          not null, primary key
#  last_name                  :string
#  last_sign_in_at            :datetime
#  last_sign_in_ip            :string
#  reset_password_sent_at     :datetime
#  reset_password_token       :string
#  sign_in_count              :integer          default(0), not null
#  terms_agreed_at            :datetime
#  uid                        :string           default(""), not null
#  unconfirmed_email          :string
#  updated_at                 :datetime
#

class Dentist < User
  self.default_scope -> { dentists }
  before_validation :generate_random_password
  before_create :assign_default_services
  after_create :assign_dentist_role

  has_many :clinic_assignments, dependent: :destroy
  has_many :clinics, through: :clinic_assignments
  has_many :appointments, through: :clinic_assignments, dependent: :destroy

  has_many :hmo_accreditations, as: :accredited, dependent: :destroy
  has_many :hmos, through: :hmo_accreditations

  has_many :service_assignments, as: :assigned, dependent: :destroy
  has_many :services, through: :service_assignments

  has_many :specializations, dependent: :destroy
  has_many :specialties, through: :specializations

  has_many :secretary_assignments, dependent: :destroy
  has_many :secretaries, through: :secretary_assignments

  has_many :favorites, as: :favorited, dependent: :destroy, class_name: 'Favorite'
  has_many :favorited_by, through: :favorites, source: :patient

  has_many :drafts, foreign_key: :dentist_id, dependent: :destroy

  has_one :profile, class_name: "DentistProfile", foreign_key: :user_id, dependent: :destroy

  def name_with_salutation
    "Dr. #{name}"
  end

  def specialization
    specialties.empty? ? "No specified specialization" : specialties.first.name
  end

  def self.hmo_filter(hmo_id)
    hmo = HMO.find(hmo_id)
    where(id: hmo.dentist_ids.uniq)
  end

  def self.service_filter(service_id)
    service = Service.find(service_id)
    where(id: service.dentist_ids.uniq)
  end

  def self.specialty_filter(specialty_id)
    specialty = Specialty.find(specialty_id)
    where(id: specialty.dentist_ids.uniq)
  end

  def activated?
    profile.activated_at?
  end

  def today_confirmed_appointments
    clinic_assignments.map{|c| c.appointments.for_today.confirmed.by_earliest}.flatten
  end

  def tomorrow_confirmed_appointments
    clinic_assignments.map{|c| c.appointments.for_tomorrow.confirmed.by_earliest}.flatten
  end

  def services_description
    if services.empty?
      'N/A'
    else
      services.alphabetical.map(&:name).join('\n')
    end
  end

  def hmo_description
    if hmos.empty?
      'N/A'
    else
      hmos.map(&:name).join(', ')
    end
  end

  def specialty_description
    if specialties.empty?
      'N/A'
    else
      specialties.map(&:name).join(', ')
    end
  end

  private

  def generate_random_password
    if self.password.blank?
      self.password = Devise.friendly_token.first(16)
    end
  end

  def assign_default_services
    if services.empty?
      services_name = ['check up', 'consultation'].map{|val| "%#{val}%"}
      default_services = Service.where('name ILIKE ANY (array[?])', services_name)
      services << default_services
    end
  end

  def assign_dentist_role
    make_dentist!
  end
end

app/controllers/admin/dentists_controller.rb
class Admin::DentistsController < AdminController
  before_action :set_dentist, except: [:index, :new, :create]
  set_tab :dentists, only: :index
  # GET /admin/dentists
  def index
    @dentists = Dentist.search(params[:q]).order(created_at: :desc).page(params[:page]).per(10)

    @dentists_data = Dentist.includes(:activations)

    respond_to do |format|
      format.html
      format.js
      format.csv { send_data @dentists_data.to_csv }
    end
  end

  # GET /admin/dentists/1
  def show
  end

  # GET /admin/dentists/new
  def new
    @dentist = Dentist.new
  end

  # GET /admin/dentists/1/edit
  def edit
  end

  # POST /admin/dentists
  def create
    @dentist = Dentist.new(permitted_dentist_params)
    @dentist.skip_confirmation!
    if @dentist.save
      @dentist.photos.upload params[:images] if params[:images]
      redirect_to admin_dentists_url, notice: 'Dentist was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/dentists/1
  def update
    @dentist.skip_reconfirmation!
    if @dentist.update(permitted_dentist_params)
      if params[:fee].present?  || params[:experience].present? || params[:color].present? || params[:license_number]
        profile = @dentist.profile
        profile.fee = params[:fee]
        profile.experience = params[:experience]
        profile.color = params[:color]
        profile.license_number = params[:license_number]
        profile.save
      end
      @dentist.photos.upload params[:images] if params[:images]
      redirect_to admin_dentists_url, notice: 'Dentist was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/dentists/1
  def destroy
    @dentist.destroy
    redirect_to admin_dentists_url, notice: 'Dentist was successfully destroyed.'
  end

  # POST /admin/dentists/1/assignment
  def assignment
    assignment_params = params.require(:clinic_assignment).permit(:clinic_id, schedules_attributes: [:day, :start_time, :end_time])
    @clinic = Clinic.find(assignment_params[:clinic_id])
    @clinic_assignment = @dentist.clinic_assignments.find_by_clinic_id(@clinic)
    if @clinic_assignment.present?
      @schedule = @clinic_assignment.schedules.build(assignment_params[:schedules_attributes])
      if @schedule.save
        redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist was successfully assigned.'
      else
        redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist was successfully failed.'
      end
    elsif assignment_params[:schedules_attributes].present?
      new_assignment = @clinic.assign @dentist
      schedule = new_assignment.schedules.build(assignment_params[:schedules_attributes])
      if schedule.save
        redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist was successfully assigned.'
      else
        redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist assignment failed.'
      end
    else
      if @clinic.assign @dentist
        redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist was successfully assigned.'
      else
        redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist assignment failed.'
      end
    end
  end

  # POST /admin/dentists/1/unassignment
  def unassignment
    assignment_params = params.require(:clinic_assignment).permit(:clinic_id)
    @clinic = Clinic.find(assignment_params[:clinic_id])
    if @clinic.unassign @dentist
      redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist was successfully unassigned.'
    else
      redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist unassignment failed.'
    end
  end

  def delete_schedule
    schedule_params = params.require(:assignment_schedule).permit(:assignment_schedule_id)
    @clinic_assignment = ClinicAssignment.find(params[:clinic_assignment_id])
    @assignment = @clinic_assignment.schedules.find(schedule_params[:assignment_schedule_id])
    if @assignment.destroy
      redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist Clinic schedule deleted.'
    else
      redirect_to edit_admin_dentist_url(@dentist), notice: 'Dentist Clinic schedule deleted.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dentist
    @dentist = Dentist.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def permitted_dentist_params
    params.require(:dentist).permit(:first_name, :last_name, :email,
                                    :mobile_number, :birthdate, :password,
                                    :password_confirmation, :avatar,
                                    service_ids: [], hmo_ids: [],
                                    specialty_ids: [])
  end
end

app/controllers/api/v1/dentists.rb
module API
  module V1
    class Dentists < Grape::API
      include Grape::Kaminari
      resources :s do
        resources :dentists do
          desc 'Return list of Dentists with optional search parameter'
          params do
            optional :query, type: String, desc: 'Name of dentist being searched'
          end
          get jbuilder: 'v1/dentists/index' do
            @dentists = current_user.dentists.search(params[:query])
          end

          desc 'Return dentist UID before adding with activation code'
          params do
            optional :activation_code, type: String, desc: 'Activation code of dentist to add'
          end
          get '/uid' do
            dentist_profile = DentistProfile.find_by!(activation_code: params[:activation_code])
            unless current_user.dentist_ids.include?(dentist_profile.user.id)
              { uid: "#{dentist_profile.user.uid}" }
            else
              error!('Dentist already added', 500)
            end
          end
        end

        resources :dentist do
          route_param :uid do
            paginate per_page: 5
            desc 'Get dentist confirmed appointments history'
            get '/history', jbuilder: 'v1/appointments/confirmed_history' do
              @dentist = Dentist.find_by!(uid: params[:uid])
              @appointments =  paginate(Kaminari.paginate_array(@dentist.clinic_assignments.map{|c| c.appointments.confirmed_appointments.by_latest}.flatten.group_by{|a| a.schedule.to_date }.to_a))
            end

            desc 'Add new dentist to manage'
            post '/add' do
              dentist = Dentist.find_by!(uid: params[:uid])
              if current_user.add_dentist(dentist)
                { message: 'Dentist succesfully added'}
              else
                error!('Dentist already added', 400)
              end
            end

            desc 'Get dentist profile'
            get '/', jbuilder: 'v1/dentists/show' do
              @dentist = current_user.dentists.find_by!(uid: params[:uid])
            end

            desc 'Edit dentist profile and basic information'
            params do
              optional :avatar, type: Rack::Multipart::UploadedFile, desc: 'Dentist\'s avatar'
              optional :license_number, type: String, desc: 'Dentist\'s license number'
              optional :experience, type: String, desc: 'Dentist\'s years of experience'
              optional :fee, type: String, desc: 'Dentist\'s fee'
              optional :specialties, type: String, desc: 'Dentist\'s specialties'
              optional :hmos, type: String, desc: 'Dentist\'s HMO accreditations'
              optional :services, type: String, desc: 'Dentist\'s offered services'
              optional :schedules, type: String, desc: "Dentist's schedules in DAY;START_DATE;END_DATE|DAY... encoded in BASE64"
              optional :clinic_assignment_id, type: String, desc: "Dentist clinic assignment id"
            end
            post '/edit', jbuilder: 'v1/dentists/show' do
              handler = DraftHandler.new(current_user, params, classification: "Edit dentist profile and basic information").create
              if handler.response[:success]
                @dentist = handler.response[:details]
              else
                error!(handler.response[:details], 500)
              end
            end

            desc 'Delete dentist'
            delete '/delete' do
              @dentist = current_user.dentists.find_by!(uid: params[:uid])
              unless current_user.dentists.delete(@dentist)
                error!("Dentist failed to be deleted", 400)
              else
                { message: "Dentist deleted from secretary's list" }
              end
            end
          end
        end
      end

      resources :dentist do
        route_param :uid do
          desc 'Return Dentist data'
          get '/show', jbuilder: 'v1/dentists/show' do
            @dentist = Dentist.find_by!(uid: params[:uid])
          end
        end
      end
    end
  end
end

app/helpers/admin/dentists_helper.rb
module Admin::DentistsHelper

  def format_schedule a
    "#{a.abbr_day_name_upcased}, #{a.start_time.strftime('%l %p')} - #{a.end_time.strftime('%l %p')}"
  end

end

app/views/admin/dentists/_clinic_assignment_form.html.erb
<hr>

<h4>Clinic Assignments</h4>
<p><%= notice %></p>

<% if @dentist.clinics.empty? %>
  <p>Dentist has not been assigned yet.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Clinic</th>
        <th>Assigned on</th>
        <th>Schedule</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @dentist.clinic_assignments.each do |assignment| %>
        <tr>
          <td><%= assignment.clinic.name %></td>
          <td><%= assignment.created_at %></td>
          <td>
            <% if assignment.schedules.present? %>
              <ul>
                <% assignment.schedules.order(day: :asc).each do |a| %>
                  <%= form_for [:admin, a], url: admin_dentist_delete_schedule_path(@dentist, assignment), method: :delete do |f| %>
                    <%= f.hidden_field :assignment_schedule_id, value: a.id %>
                    <li>
                      <%= format_schedule(a) %>
                      <%= f.submit '&cross;'.html_safe, class: 'button tiny alert' %>
                    </li>
                  <% end %>
                <% end %>
              </ul>
            <% end %>
          </td>
          <td>
            <%= form_for [:admin, assignment], url: admin_dentist_unassignment_path(@dentist), method: :post do |f| %>

              <%= f.hidden_field :clinic_id, value: assignment.clinic_id %>
              <%= f.submit '&cross;'.html_safe, class: 'button tiny alert' %>

            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<hr>

<%= form_for [:admin, @dentist.clinic_assignments.build], url: admin_dentist_assignment_path(@dentist) do |f| %>

  <%= f.select :clinic_id, clinic_choices %>
    <%= f.fields_for :schedules_attributes do |f| %>
      <label>Days: </label>
      <%= f.select :day, Date::DAYNAMES.zip((0..6).to_a), include_blank: true %>
      <label>Start time: </label>
      <%= f.time_field :start_time %>
      <label>End time: </label>
      <%= f.time_field :end_time %>
    <% end %>
  <%= f.submit 'Assign', class: 'button' %>

<% end %>

app/views/admin/dentists/_dentists.html.erb
<table class="clean">
  <thead>
    <tr>
      <th width="<%= user_avatar_default_dimension %>"></th>
      <th width="300">Name</th>
      <th width="100">Email</th>
      <th width="100">Activation Code</th>
      <th width="150">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @dentists.each do |dentist| %>
    <tr>
    <td>
      <%= image_tag dentist.avatar.url, width: user_avatar_default_dimension, height: user_avatar_default_dimension %>
    </td>
    <td> <%= "#{dentist.first_name} #{dentist.last_name}" %> </td>
    <td> <%= dentist.email %> </td>
    <td> <%= dentist.profile.activation_code %> </td>
    <td>
      <%= link_to 'Edit', edit_admin_dentist_path(dentist), class: 'admin-custom-btn edit' %>
      <%= link_to 'Delete', admin_dentist_path(dentist), class: 'admin-custom-btn alert', method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/admin/dentists/_form.html.erb
<%= form_for [:admin, @dentist] do |f| %>
  <% if @dentist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dentist.errors.count, "error") %> prohibited this dentist from being saved:</h2>

      <ul>
        <% @dentist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :avatar, value: nil, id: 'encoded_file_field' %>

  <%= render partial: "shared/croppable_avatar", locals: { avatar_source: @dentist  } %>

  <hr />

  <div class="row">
    <div class="small-12 large-12 columns">
      <%= f.file_field :avatar %>
      <small>NOTE: Photo should have square dimension and atleast be 800px in width.</small>
    </div>
  </div>

  <br>

  <label>
    First Name: <%= f.text_field :first_name %>
  </label>

  <label>
    Last Name: <%= f.text_field :last_name %>
  </label>

  <label>
    Email: <%= f.text_field :email %>
  </label>

  <label>
    Mobile #: <%= f.text_field :mobile_number %>
  </label>

  <label>
    Birthdate: <%= f.date_field :birthdate, value: @dentist.birthdate.try(:to_date) %>
  </label>

  <% if @dentist.profile.present? %>
    <hr>
    <h4>Profile</h4>
    <label>
      Consultation Fee: <%= text_field_tag :fee, @dentist.profile.fee %>
    </label>

    <label>
      Experience: <%= text_field_tag :experience, @dentist.profile.experience %>
    </label>

    <label>
      License Number: <%= text_field_tag :license_number, @dentist.profile.license_number %>
    </label>

    <label>
      Color: <%= color_field_tag :color, @dentist.profile.color %>
    </label>
  <% end %>

  <hr>
  <h4>Specialties</h4>

  <%= hidden_field_tag "dentist[specialty_ids][]", nil %>
  <% Specialty.order(name: :asc).each do |specialty| %>
    <%= check_box_tag "dentist[specialty_ids][]", specialty.id, @dentist.specialties.include?(specialty), id: dom_id(specialty) %>
    <%= label_tag dom_id(specialty), specialty.name %> <br>
  <% end%>

  <hr>
  <h4>Services</h4>

  <%= hidden_field_tag "dentist[service_ids][]", nil %>
  <% Service.order(name: :asc).each do |service| %>
    <%= check_box_tag "dentist[service_ids][]", service.id, @dentist.services.include?(service), id: dom_id(service) %>
    <%= label_tag dom_id(service), service.name %> <br>
  <% end%>

  <hr>
  <h4>HMOs</h4>

  <%= hidden_field_tag "dentist[hmo_ids][]", nil %>
  <% HMO.order(name: :asc).each do |hmo| %>
    <%= check_box_tag "dentist[hmo_ids][]", hmo.id, @dentist.hmos.include?(hmo), id: dom_id(hmo) %>
    <%= label_tag dom_id(hmo), hmo.name %> <br>
  <% end%>

  <hr>
  <h4>Photos</h4>
  <label>
    NOTE: Photo should have square dimension and atleast be 800px in width.
  </label>
  <br>

  <% if @dentist.photos.blank? %>
    <p>No dentist photos.</p>
  <% else %>
    <% @dentist.photos.map do |photo| %>
      <div style="background-image:url(<%= photo.image.url(:medium) %>)" class="photos-grid">
        <%= link_to 'X', admin_photo_path(photo),
          data: { confirm: 'Are you sure?' },
          method: :delete, remote: true,
          class: "destroy-photo" %>
        </div>
      <% end %>
    <% end %>
    <hr>
    <%= file_field_tag "images[]", type: :file, multiple: true %>

    <div class="actions">
      <%= f.submit 'Submit', class: 'button'%>
    </div>
  <% end %>

app/views/admin/dentists/edit.html.erb
<h4>Editing dentist</h4>
<%= render 'form' %>
<%= render 'clinic_assignment_form' %>

app/views/admin/dentists/index.html.erb
<% content_for :title, 'Dentists' %>
<%= content_tag(:p, notice, id: "notice") if notice %>

<h5 class="header">Dentists</h5>
<div class="right">
  <%= link_to 'NEW', new_admin_dentist_path, class: 'admin-btn new' %></small>
  <%= link_to "EXPORT TO CSV", admin_dentists_path(format: "csv"), class: 'admin-btn export' %>
</div>

<%= form_tag admin_dentists_path, method: :get, remote: true, class: "admin-search-bar" do %>
  <%= text_field_tag :q, nil, placeholder: "Search" %>
<% end %>

<div id="dentistLists">
  <%= render 'dentists' %>
</div>
<div id="paginator">
  <%= paginate @dentists, remote: true %>
</div>

app/views/admin/dentists/index.js.erb
$("#dentistLists").html("<%= escape_javascript(render("dentists")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@dentists, remote: true)) %>");

app/views/admin/dentists/new.html.erb
<h4>New dentist</h4>
<%= render 'form' %>

app/views/admin/dentists/show.html.erb
<p id="notice"><%= notice %></p>

<label>
  Name: <%= "#{@dentist.first_name} #{@dentist.last_name}" %>
</label>

<label>
  Email: <%= @dentist.email %>
</label>

<label>
  Mobile #: <%= @dentist.mobile_number %>
</label>

<label>
  Birthdate: <%= @dentist.birthdate %>
</label>