config/routes.rb
Rails.application.routes.draw do

  mount API::Root => "/"
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  scope '/tmpi' do
    get "/", to: "tmpi#index", as: "tmpi_index"
    post "/:id/confirm", to: "tmpi#confirm", as: "tmpi_confirm"
    post "/:id/decline", to: "tmpi#decline", as: "tmpi_decline"
  end
  get "support", to: "support#index"
  get "funfacts", to: "home#funfacts"
  post "support", to: "support#feedback", as: "submit_feedback"
  get "successful_password_change", to: "home#successful_password_change"

  scope "/cms" do
    unauthenticated :user do
      devise_scope :user do
        root to: "devise/sessions#new", as: "unauthenticated_root"
      end
    end

    authenticated :user do
      root to: "admin#index"
    end

    post "admin/dentists/:id/assignment",
      to: "admin/dentists#assignment",
      as: "admin_dentist_assignment"
    post "admin/dentists/:id/unassignment",
      to: "admin/dentists#unassignment",
      as: "admin_dentist_unassignment"
    delete "admin/dentists/:id/assignment/:clinic_assignment_id/schedule",
      to: "admin/dentists#delete_schedule",
      as: "admin_dentist_delete_schedule"
    post "admin/users/:id/toggle_status",
      to: "admin/users#toggle_status",
      as: "admin_toggle_user_status"

    get "admin/users/graph", to: "admin/users#graph"
    get "admin/appointments/graph", to: "admin/appointments#graph"

    get "admin/patients/appointments/graph", to: "admin/patients#graph"
    get "admin/patients/graph", to: "admin/patients#patients_graph"

    get "admin/secretaries/appointments/graph", to: "admin/secretaries#graph"
    get "admin/secretaries/graph", to: "admin/secretaries#secretaries_graph"

    get "admin/location/provinces", to: "admin/cities#provinces"

    get "admin/clinics/map", to: "admin/clinics#map"

    get "admin/rally_exports",
      to: "admin/rally_exports#registered_users",
      as: "admin_rally_exports"

    post "admin/users/:id/resend_code",
      to: "admin/users#resend_code",
      as: "admin_resend_user_code"

    get "admin/sms", to: "admin/sms#index", as: "admin_sms"
    post "admin/sms", to: "admin/sms#change", as: "admin_sms_change"

    authenticate :user do
      namespace :admin do
        resources :appointments, only: [:index, :show, :new, :create]
        resources :cities, only: [:index, :update]
        resources :clinics, except: :show
        resources :dentists
        resources :drafts, only: [:index, :update]
        resources :faqs, except: :show
        resources :feedbacks
        resources :hmos
        resources :patients
        resources :partner_signups, only: [:index, :update]
        resources :photos, only: [:destroy]
        resources :ratings, only: [:index, :show]
        resources :rating_suggestions, except: :show
        resources :secretaries
        resources :services
        resources :specialties
        resources :symptoms
        resources :users, only: [:index, :show, :edit, :update]
        resources :app_versions, except: [:new]
      end
    end
    devise_for :users, controllers: { passwords: "passwords" }
  end

  get "ios", to: "home#ios", as: "ios"
  get "download", to: "home#download", as: "mobile_download"
  # TODO : Uncomment on development
  # get '/rails/mailers' => "rails/mailers#index"
  # get '/rails/mailers/*path' => "rails/mailers#preview"
  get "docs", to: 'docs#index', as: 'docs'

  # Redirect all unknown path
  # and root to 404
  return404 = proc { [404, {}, [""]] }
  get "/", to: return404
  match "*path", to: return404, via: :get
end

app/models/clinic.rb
# == Schema Information
#
# Table name: clinics
#
#  address           :string
#  city_id           :integer
#  created_at        :datetime         not null
#  id                :integer          not null, primary key
#  landline          :string
#  landmarks         :string
#  lat               :float
#  lng               :float
#  logo_content_type :string
#  logo_file_name    :string
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#  mobile_number     :string
#  name              :string
#  parking_slot      :string
#  price             :string
#  updated_at        :datetime         not null
#

class Clinic < ActiveRecord::Base
  geocoded_by :address, latitude: :lat, longitude: :lng
  after_validation :geocode, if: ->(obj){ obj.address.present? && obj.address_changed? }

  has_attached_file :logo, :styles => { medium: '300x300#', thumb: '100x100#', small: '50x50#' }, default_url: 'icon.png'
  validates_attachment_content_type :logo, :content_type => /\Aimage\/(jpg|jpeg|png)\z/, :message => 'only .jpg, .jpeg, or .png images'
  before_post_process :rename_logo

  validates :name, uniqueness: true
  validates_presence_of :name, :address

  validate :city_existence
  belongs_to :city

  has_many :clinic_assignments, dependent: :destroy
  has_many :photos, as: :imageable, dependent: :destroy
  has_many :dentists, through: :clinic_assignments
  has_many :secretary_assignments, through: :dentists
  has_many :favorites, as: :favorited, dependent: :destroy, class_name: 'Favorite'
  has_many :favorited_by, through: :favorites, source: :patient
  has_many :received_ratings, as: :ratee, class_name: 'Rating'
  has_many :raters, through: :received_ratings, source_type: 'Patient'

  has_many :hmo_accreditations, as: :accredited, dependent: :destroy
  has_many :hmos, through: :hmo_accreditations

  has_many :service_assignments, as: :assigned, dependent: :destroy
  has_many :services, through: :service_assignments

  def secretaries
    Secretary.includes(:roles, :activations, secretary_assignments: [:dentist]).where("users.id IN (?)", dentists.map(&:secretaries).flatten.uniq)
  end

  def activated_secretaries
    secretaries.where.not(activations: { activated_at: nil })
  end

  def parking_slot
    read_attribute(:parking_slot).blank? ? "Without parking" : read_attribute(:parking_slot)
  end

  def schedules
    clinic_assignments.map { |c| c.schedules }.flatten.uniq
  end

  def days
    schedules.sort_by(&:day).map { |s| s.day }.flatten.uniq
  end

  def schedule_data
    if schedules.present?
      @start_time = schedules.min_by(&:start_time).start_time
      @end_time = schedules.max_by(&:end_time).end_time
      @start_day = schedules.min_by(&:day)
      @end_day = schedules.max_by(&:day)
      @days = schedules.sort_by(&:day)
    end
  end

  def display_schedule
    if schedules.present?
      schedule_data
      "#{@start_day.abbr_day_name_upcased} - #{@end_day.abbr_day_name_upcased} #{@start_time.strftime('%l:%M %p')} -#{@end_time.strftime('%l:%M %p')}"
    else
      "No schedule provided"
    end
  end

  def schedule_per_day
    if schedules.present?
      schedule_data
      @days.map { |s| "#{s.abbr_day_name_upcased} #{s.start_time.strftime('%l:%M %p')} -#{s.end_time.strftime('%l:%M %p')}" }
    else
      []
    end
  end

  def is_open?
    return false if schedules.empty?
    if schedule_for_today = schedules.select{|s| s.day == DateTime.now.utc.wday}.first
      time = Time.now.utc + (8*60*60)
      open_time = schedule_for_today.start_time
      close_time = schedule_for_today.end_time
      # http://stackoverflow.com/a/28546184
      (((time.to_r / 60 / 60 / 24) % 1) >= ((open_time.to_r / 60 / 60 / 24) % 1)) && (((time.to_r / 60 / 60 / 24) % 1) <= ((close_time.to_r / 60 / 60 / 24) % 1))
    else
      false
    end
  end

  def is_schedule_continous?
    return false if days.count == 1
    (0..6).each_cons(days.count).any? { |d| d == days }
  end

  def operation_status
    if schedules.present?
      is_open? ? "OPEN TODAY" : "CLOSED"
    else
      "UNKNOWN"
    end
  end

  def self.search q = nil
    query = "%#{q}%"
    where('name ILIKE ?', query)
  end

  def assign(dentist)
    ClinicAssignment.create dentist_id: dentist.id, clinic_id: self.id
  end

  def unassign(dentist)
    assignment = ClinicAssignment.where(clinic_id: self.id, dentist_id: dentist.id).first
    return false unless assignment
    assignment.destroy
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << ["Name","Mobile Number","Address","City","Province","Latitude","Longitude","created_at"]

      all.each do |clinic|
        csv << [clinic.name, clinic.mobile_number, clinic.address, clinic.city.try(:name), (clinic.city.province.name if clinic.city.province.present?), clinic.lat, clinic.lng, clinic.created_at]
      end
    end
  end

  private

  def rename_logo
    extension = File.extname(logo_file_name).downcase
    self.logo.instance_write :file_name, "#{SecureRandom.uuid}#{extension}"
  end

  def city_existence
    self.errors.add(:city, "must exist") unless City.exists?(id: city_id)
  end
end

app/controllers/admin/clinics_controller.rb
class Admin::ClinicsController < AdminController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]
  set_tab :clinics
  set_tab :clinics_list, :submenu, except: %w(map)
  set_tab :clinics_map, :submenu, only: %w(map)
  # GET /admin/clinics
  def index
    @clinics = Clinic.search(params[:q]).order(created_at: :desc).page(params[:page]).per(10)

    @clinic_data = if params[:type] == "all"
                     Clinic.all
                   elsif params[:type] == "activated"
                     Clinic.where(id: Clinic.all.map{|c| c.id unless c.activated_secretaries.blank? }.compact)
                   end

    respond_to do |format|
      format.html
      format.js
      format.csv { send_data @clinic_data.to_csv }
    end
  end

  # GET /admin/clinics/1
  def show
  end

  # GET /admin/clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /admin/clinics/1/ediActionController::Base.helpers.asset_path(t
  def edit
  end

  # POST /admin/clinics
  def create
    @clinic = Clinic.new(clinic_params)

    if @clinic.save
      @clinic.photos.upload params[:images] if params[:images]
      redirect_to admin_clinics_path, notice: 'Clinic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/clinics/1
  def update
    if @clinic.update(clinic_params)
      @clinic.photos.upload params[:images] if params[:images]
      redirect_to admin_clinics_path, notice: 'Clinic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/clinics/1
  def destroy
    @clinic.destroy
    redirect_to admin_clinics_path, notice: 'Clinic was successfully destroyed.'
  end

  def map
    @clinics = []
    Clinic.includes(clinic_assignments: [{dentist: [:roles, :secretary_assignments, :activations]}]).find_each do |c| 
      unless c.activated_secretaries.blank?
        @clinics << [c.name.to_s, c.mobile_number, c.address, c.lat, c.lng, (c.logo.blank? ? ActionController::Base.helpers.asset_path('Locator.png') : c.logo.url), c.dentists.map{|d| [d.avatar.url, d.name]}]
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_clinic
    @clinic = Clinic.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def clinic_params
    params.require(:clinic).permit(:name, :address, :logo, :lat, :lng, :city_id, :mobile_number, :parking_slot,  service_ids: [])
  end
end

app/controllers/api/v1/clinics.rb
module API
  module V1
    class Clinics < Grape::API

      resources :clinics do
        desc 'Return list of Clinics'
        get jbuilder: 'v1/clinics/index' do
          @clinics = Clinic.all
        end

        desc 'Search endpoint for Clinics'
        params do
          optional :query, type: String, desc: 'Name clinic to be searched'
        end
        get '/search', jbuilder: 'v1/clinics/index' do
          @clinics = Clinic.search(params[:query])
        end

        desc 'Return nearby Clinics'
        params do
          optional :lat, type: Float, desc: 'Latitude value of Patient\'s location'
          optional :lng, type: Float, desc: 'Longitude value of Patient\'s location'
        end
        get '/nearby', jbuilder: 'v1/clinics/index' do
          if params[:lat].present? && params[:lng].present?
            @clinics = Clinic.near([params[:lat], params[:lng]], 10)
          else
            @clinics = Clinic.all
          end
        end
      end

      resources :clinic do

        route_param :id do
          desc 'Return clinic data'
          get jbuilder: 'v1/clinics/show' do
            @clinic = Clinic.find_by_id(params[:id])
            unless @clinic.blank?
              @clinic
            else
              {message: 'Clinic doesn\'t exist!' }
            end
          end
        end

      end

    end
  end
end

app/helpers/admin/clinics_helper.rb
module Admin::ClinicsHelper
  def clinic_choices
    Clinic.all.map{|c| [c.name, c.id] }
  end
end

app/views/admin/clinics/_clinics.html.erb
<table class="clean">
  <thead>
    <tr>
      <th width="<%= user_avatar_default_dimension %>"></th>
      <th width="300">Name</th>
      <th width="100">Address</th>
      <th width="50">Lat</th>
      <th width="50">Lng</th>
      <th width="150">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @clinics.each do |clinic| %>
    <tr>
    <td>
      <%= image_tag clinic.logo.url, width: user_avatar_default_dimension, height: user_avatar_default_dimension %>
    </td>
    <td> <%= clinic.name %> </td>
    <td> <%= clinic.address %> </td>
    <td> <%= clinic.lat %> </td>
    <td> <%= clinic.lng %> </td>
    <td>
      <%= link_to 'Edit', edit_admin_clinic_path(clinic), class: 'admin-custom-btn edit' %>
      <%= link_to 'Delete', admin_clinic_path(clinic), class: 'admin-custom-btn alert', method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/admin/clinics/_form.html.erb
<%= form_for [:admin, @clinic], multipart: true do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
        <% @clinic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <label>
    Logo:
    <% if @clinic.logo.present? %>
      <%= image_tag @clinic.logo.url, width: 100 %>
      <br>
      <br>
    <% end %>
    <%= f.file_field :logo %>
  </label>
  <label>
    NOTE: Photo should have square dimension and atleast be 800px in width.
  </label>
  <br>

  <label>
    Name: <%= f.text_field :name %>
</label>

<label>
  Address: <%= f.text_field :address %>
  </label>

  <label>
    Parking Slot: <%= f.text_field :parking_slot %>
</label>

  <label>
    Mobile Number: <%= f.text_field :mobile_number %>
</label>

<label>
  Lat: <%= f.text_field :lat %>
  </label>

  <label>
    Lng: <%= f.text_field :lng %>
</label>

<label>
  City: <%= f.select :city_id, city_choices %>
  </label>

  <hr>
  <h4>Services</h4>

  <%= hidden_field_tag "clinic[service_ids][]", nil %>
  <% Service.all.each do |service| %>
    <%= check_box_tag "clinic[service_ids][]", service.id, @clinic.services.include?(service), id: dom_id(service) %>
    <%= label_tag dom_id(service), service.name %> <br>
  <% end%>

  <hr>
  <h4>Photos</h4>
  <label>
    NOTE: Photo should have square dimension and atleast be 800px in width.
  </label>
  <br>
  <% if @clinic.photos.blank? %>
    <p>No clinic photos.</p>
  <% else %>
    <% @clinic.photos.map do |photo| %>
      <div style="background-image:url(<%= photo.image.url(:medium) %>)" class="photos-grid">
        <%= link_to 'X', admin_photo_path(photo),
          data: { confirm: 'Are you sure?' },
          method: :delete, remote: true,
          class: "destroy-photo" %>
      </div>
    <% end %>
  <% end %>
  <hr>
  <%= file_field_tag "images[]", type: :file, multiple: true %>

  <%= f.submit 'Submit', class: 'button' %>
<% end %>

app/views/admin/clinics/edit.html.erb
<h4>Edit clinic</h4>
<%= render 'form' %>

app/views/admin/clinics/index.html.erb
<% content_for :title, 'Clinics' %>
<%= content_tag(:p, notice, id: "notice") if notice %>

<h5 class="header">Clinics</h5>
<div class="right">
  <%= link_to 'NEW', new_admin_clinic_path, class: 'admin-btn new' %></small>
  <%= link_to "EXPORT TO CSV", admin_clinics_path(format: "csv", type: "all"), class: 'admin-btn export' %>
  <%= link_to "EXPORT TO CSV [Activated]", admin_clinics_path(format: "csv", type: "activated"), id: 'Test1', class: 'admin-btn export' %>
</div>

<%= form_tag admin_clinics_path, method: :get, remote: true, class: "admin-search-bar" do %>
    <%= text_field_tag :q, nil, placeholder: "Enter clinic's name here..." %>
<% end %>

<div id="clinicLists">
  <%= render 'clinics' %>
</div>
<div id="paginator">
  <%= paginate @clinics, remote: true %>
</div>

app/views/admin/clinics/index.js.erb
$("#clinicLists").html("<%= escape_javascript(render("clinics")) %>");
$("#paginator").html("<%= escape_javascript(paginate(@clinics, remote: true)) %>");

app/views/admin/clinics/map.html.erb
<div id="map" style="height: 100%"></div>

<script>
var clinics = [
  <% @clinics.each do |clinic| %>
  {
    name:     "<%= clinic[0] %>",
    mobile:   "<%= clinic[1] %>",
    address:  "<%= clinic[2] %>",
    lat:      "<%= clinic[3] %>",
    lng:      "<%= clinic[4] %>",
    logo:     "<%= clinic[5] %>",
    dentists: [
      <% clinic[6].each do |dentist| %>
        {
          avatar: "<%= dentist[0] %>",
          name:   "<%= dentist[1] %>"
        },
      <% end %>
    ]
  },
  <% end %>
];
// This example displays a marker at the center of Australia.
// When the user clicks the marker, an info window opens.

function initMap() {
 
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 13,
    center: {lat: 14.6041051, lng: 121.0167159}
  });
  
  var infowindow = new google.maps.InfoWindow();
  var marker, i, stringContent, d, lists;

  for (i = 0; i < clinics.length; i++) {
    var icon = {
      url: clinics[i]["logo"], // url
      scaledSize: new google.maps.Size(30, 30), // scaled size
      origin: new google.maps.Point(0,0), // origin
      anchor: new google.maps.Point(0, 0) // anchor
    };
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(clinics[i]["lat"],clinics[i]["lng"]),
      map: map,
      icon: icon,
      title: clinics[i]["name"]
    });
    marker.setMap(map);
    google.maps.event.addListener(marker, 'click', (function(marker, i) {
      return function() {
          lists = '';
          for (d = 0; d < clinics[i]["dentists"].length; d++) {
            lists += '<li>';
            lists += '<div class="dentist-image" style="background-image:url('+clinics[i]["dentists"][d]["avatar"]+')"></div>';
            lists += '<span>'+clinics[i]["dentists"][d]["name"]+'</span>';
            lists += '</li>';
          }
        stringContent = '<div class="map-clinic-details-container">'+
                          '<h1>'+clinics[i]["name"]+'</h1>'+
                          '<table>'+
                            '<tr>'+
                              '<td>Tel No:</td>'+
                              '<td>'+clinics[i]["mobile"]+'</td>'+
                            '</tr>'+
                            '<tr>'+
                              '<td>Address:</td>'+
                              '<td>'+clinics[i]["address"]+'</td>'+
                            '</tr>'+
                          '</table>'+
                          '<div class="dentists">'+
                            '<label>Dentists:</label>'+
                            '<ul>'+
                             lists+
                            '</ul>'+
                          '</div>'+
                        '</div>';
        infowindow.setContent(stringContent);
        infowindow.open(map, marker);

        var iwOuter = $('.gm-style-iw');

        var iwBackground = iwOuter.prev();
        iwBackground.children(':nth-child(2)').css({'display' : 'none'});
        iwBackground.children(':nth-child(4)').css({'display' : 'none'});
        iwBackground.children(':nth-child(3)').children(':first-of-type').children().css({'background-color': '#38B4B3','box-shadow':'none'})
        iwBackground.children(':nth-child(3)').children(':last-of-type').children().css({'background-color': '#38B4B3','box-shadow':'none'})
        var iwCloseBtn = iwOuter.next();
        iwCloseBtn.css({
          opacity: '1',
          right: '27px',
          top: '25px',
        });

        iwCloseBtn.mouseout(function(){
          $(this).css({opacity: '1'});
        });
      }
    })(marker, i));
  }
}
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap"></script>

app/views/admin/clinics/new.html.erb
<h4>New clinic</h4>
<%= render 'form' %>

app/views/admin/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_clinic_path(@clinic) %> |
<%= link_to 'Back', admin_clinics_path %>